/** Loading the two surfaces the parity check compares, and the registry between them. */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { buildServer } from "../../src/server";
import type { DivergenceKind, JsonSchema, Normalization } from "./compare";

/**
 * Generated by `uv run python -m tests.surface_manifest` in mcp-server-galaxy-py.
 * Living outside this package is the point: it is the other server's contract, and
 * a copy kept on this side is what rotted last time.
 */
const MANIFEST_URL = new URL(
  "../../../../../mcp-server-galaxy-py/tests/testdata/mcp-surface.json",
  import.meta.url,
);

const REGISTRY_URL = new URL("../fixtures/accepted-divergences.json", import.meta.url);

export interface ManifestTool {
  name: string;
  tags: string[];
  /** Set when the Python server registers the tool only under an optional extra. */
  conditionalOn?: string;
  inputSchema: JsonSchema;
}

export interface Manifest {
  source: string;
  toolCount: number;
  tools: ManifestTool[];
}

export type DivergenceStatus = "intentional" | "pending-port" | "pending-decision" | "unreviewed-gap";

export const DIVERGENCE_STATUSES: readonly DivergenceStatus[] = [
  "intentional",
  "pending-port",
  "pending-decision",
  "unreviewed-gap",
];

export interface AcceptedDivergence {
  tool: string;
  param: string | null;
  kind: DivergenceKind;
  observed: string;
  status: DivergenceStatus;
  reason: string;
}

export interface NormalizationRule {
  enabled: boolean;
  status: DivergenceStatus;
  reason: string;
}

export interface Registry {
  normalization: Record<keyof Normalization, NormalizationRule>;
  divergences: AcceptedDivergence[];
}

function readJson<T>(url: URL, what: string): T {
  const path = fileURLToPath(url);
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch (err) {
    throw new Error(`cannot read the ${what} at ${path}: ${(err as Error).message}`);
  }
}

export function loadManifest(): Manifest {
  return readJson<Manifest>(MANIFEST_URL, "Python surface manifest");
}

export function loadRegistry(): Registry {
  return readJson<Registry>(REGISTRY_URL, "accepted-divergence registry");
}

export function normalizationFrom(registry: Registry): Normalization {
  return {
    snakeCaseParamNames: registry.normalization.snakeCaseParamNames.enabled,
    pythonNullDefaults: registry.normalization.pythonNullDefaults.enabled,
  };
}

export function pythonSurface(manifest: Manifest): Record<string, JsonSchema> {
  return Object.fromEntries(manifest.tools.map((t) => [t.name, t.inputSchema]));
}

/**
 * What an MCP client actually sees from this package -- asked of a running server
 * rather than rebuilt from the op shapes, so a registration bug shows up here too.
 */
export async function typescriptSurface(): Promise<Record<string, JsonSchema>> {
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const server = buildServer({ baseUrl: "https://galaxy.invalid", apiKey: "not-used" });
  const client = new Client({ name: "parity-check", version: "0" });
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  try {
    const { tools } = await client.listTools();
    return Object.fromEntries(tools.map((t) => [t.name, t.inputSchema as JsonSchema]));
  } finally {
    await client.close();
    await server.close();
  }
}
