/** Loading the two surfaces the parity check compares, and the registry between them. */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { allOperations } from "@galaxyproject/galaxy-ops";
import { buildServer } from "../../src/server";
import {
  describe as describeValue,
  isPlainObject,
  read,
  surfaceByName,
  NORMALIZATION_RULES,
  type DivergenceKind,
  type OtherSide,
  type JsonSchema,
  type Normalization,
  type NormalizationRuleName,
  type ResultShape,
  type Surface,
  type ToolAnnotations,
  type ToolContract,
} from "./compare";

/**
 * Generated by `uv run python -m tests.surface_manifest` in mcp-server-galaxy-py.
 * Living outside this package is the point: it is the other server's contract, and
 * a copy kept on this side is what rotted last time.
 */
const MANIFEST_URL = new URL(
  "../../../../../mcp-server-galaxy-py/tests/testdata/mcp-surface.json",
  import.meta.url,
);

const REGISTRY_URL = new URL("../fixtures/accepted-divergences.json", import.meta.url);

export interface ManifestTool {
  name: string;
  tags: string[];
  /** Set when the Python server registers the tool only under an optional extra. */
  conditionalOn?: string;
  /** Written only for a tool that declares a lower bound on the Galaxy it runs against. */
  requires?: { galaxy: string };
  /** The MCP annotations the Python tool advertises; empty when it advertises none. */
  annotations: ToolAnnotations;
  inputSchema: JsonSchema;
}

export interface Manifest {
  source: string;
  toolCount: number;
  tools: ManifestTool[];
}

export type DivergenceStatus = "intentional" | "pending-port" | "pending-decision" | "unreviewed-gap";

export const DIVERGENCE_STATUSES: readonly DivergenceStatus[] = [
  "intentional",
  "pending-port",
  "pending-decision",
  "unreviewed-gap",
];

export interface AcceptedDivergence {
  tool: string;
  param: string | null;
  kind: DivergenceKind;
  observed: string;
  status: DivergenceStatus;
  reason: string;
}

export interface NormalizationRule {
  enabled: boolean;
  status: DivergenceStatus;
  reason: string;
}

export interface Ratchet {
  unreviewedGaps: number;
}

export interface Registry {
  normalization: Record<NormalizationRuleName, NormalizationRule>;
  ratchet: Ratchet;
  divergences: AcceptedDivergence[];
}

/**
 * The status the registry is not allowed to accumulate: a difference the comparator
 * found and nobody has ruled on. Everything else is somebody's decision and can be
 * argued with; this one is just a pile.
 */
export const RATCHETED_STATUS: DivergenceStatus = "unreviewed-gap";

/**
 * How many divergences of the ratcheted status the registry says it may hold.
 * Read rather than reached for, so everything that shows this number -- the check
 * and the report -- refuses the same unreadable registry with the same words.
 */
export function ratchetCeiling(registry: Registry): number {
  const node = registry as unknown as Record<string, unknown>;
  const declared = (read(node, "ratchet", "object", "the registry") ?? {}) as Record<
    string,
    unknown
  >;
  const allowed = read(declared, "unreviewedGaps", "count", "the registry's ratchet");
  if (allowed === undefined) {
    throw new Error(
      `the registry does not say how many "${RATCHETED_STATUS}" divergences it may hold, and ` +
        "that number is the only thing stopping the pile growing",
    );
  }
  return allowed as number;
}

/**
 * What the ratchet has to say about the registry as it stands.
 *
 * Counted over the registry's own entries rather than over the live divergences,
 * which is the same number: the two tests either side of this one fail the moment
 * the registry lists a divergence the surfaces no longer support or misses one they
 * do. A malformed declaration throws instead -- a count that cannot be read is not
 * a parity problem, it is a registry nobody can check.
 */
export function ratchetProblems(registry: Registry): string[] {
  const ceiling = ratchetCeiling(registry);
  const held = registry.divergences.filter((d) => d.status === RATCHETED_STATUS).length;
  if (held > ceiling) {
    return [
      `the registry holds ${held} "${RATCHETED_STATUS}" divergences where ${ceiling} is the most ` +
        "it may hold. A new one needs somebody to read both sides and give it a reviewed status " +
        "and a reason, or the gap closed in the op -- not a bigger number in `ratchet`.",
    ];
  }
  if (held < ceiling) {
    return [
      `the registry holds ${held} "${RATCHETED_STATUS}" divergences and says it may hold ` +
        `${ceiling}. Lower \`ratchet.unreviewedGaps\` to ${held}: a number left above the real ` +
        "count is room for the next one to arrive unnoticed.",
    ];
  }
  return [];
}

function readJson<T>(url: URL, what: string): T {
  const path = fileURLToPath(url);
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch (err) {
    throw new Error(`cannot read the ${what} at ${path}: ${(err as Error).message}`);
  }
}

export function loadManifest(): Manifest {
  return readJson<Manifest>(MANIFEST_URL, "Python surface manifest");
}

export function loadRegistry(): Registry {
  return readJson<Registry>(REGISTRY_URL, "accepted-divergence registry");
}

/** Every rule the comparator knows about, switched by the registry. */
export function normalizationFrom(registry: Registry): Normalization {
  const node = registry as unknown as Record<string, unknown>;
  const written = (read(node, "normalization", "object", "the registry") ?? {}) as Record<
    string,
    unknown
  >;
  // Read as the registry's own entries: looked up on an object, a rule named like
  // something every object answers to would be found whether it wrote one or not.
  const declared = new Map(Object.entries(written));
  const switches: [NormalizationRuleName, boolean][] = [];
  for (const name of NORMALIZATION_RULES) {
    const rule = declared.get(name);
    if (!rule) throw new Error(`the registry does not declare the "${name}" normalization rule`);
    if (!isPlainObject(rule)) {
      throw new Error(`the registry's "${name}" rule is ${describeValue(rule)}, not a rule`);
    }
    const enabled = read(rule, "enabled", "boolean", `the registry's "${name}" rule`);
    if (enabled === undefined) {
      throw new Error(`the registry does not say whether "${name}" is enabled`);
    }
    switches.push([name, enabled as boolean]);
  }
  return Object.fromEntries(switches) as Normalization;
}

export function pythonSurface(manifest: Manifest): Surface {
  const node = manifest as unknown as Record<string, unknown>;
  const tools = read(node, "tools", "list", "the manifest");
  if (tools === undefined) throw new Error("the manifest does not list any tools");
  return surfaceByName(
    (tools as unknown[]).map((entry, index) => {
      const where = `the manifest's tool ${index}`;
      if (!isPlainObject(entry)) {
        throw new Error(`${where} is ${describeValue(entry)}, not a tool`);
      }
      const name = read(entry, "name", "string", where);
      if (name === undefined) throw new Error(`${where} has no name`);
      const about = `${name as string} (manifest)`;
      // Each of these is read rather than defaulted: a manifest that stopped
      // recording one would quietly take the comparison back to guessing.
      const annotations = read(entry, "annotations", "object", about);
      if (annotations === undefined) {
        throw new Error(`the manifest does not say what ${name as string} advertises`);
      }
      const inputSchema = read(entry, "inputSchema", "object", about);
      if (inputSchema === undefined) {
        throw new Error(`the manifest does not say what ${name as string} takes`);
      }
      const tags = read(entry, "tags", "names", about);
      if (tags === undefined) {
        throw new Error(`the manifest does not say how ${name as string} is tagged`);
      }
      // Absent for most tools, so unlike the fields above this one is read rather
      // than demanded; what it has to look like when it is there is the comparison's call.
      const requires = read(entry, "requires", "object", about) as
        | { galaxy: string }
        | undefined;
      // Written only for a tool whose result the generator could read structurally, so absent
      // here means "not stated" rather than "returns nothing".
      const result = read(entry, "result", "object", about) as ResultShape | undefined;
      return [
        name as string,
        {
          inputSchema: inputSchema as JsonSchema,
          annotations: annotations as ToolAnnotations,
          tags: tags as string[],
          requires,
          result,
        },
      ] as [string, ToolContract];
    }),
    "the manifest",
  );
}

/**
 * What an MCP client actually sees from this package -- asked of a running server
 * rather than rebuilt from the op shapes, so a registration bug shows up here too.
 */
export async function typescriptSurface(): Promise<Surface> {
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const server = buildServer({ baseUrl: "https://galaxy.invalid", apiKey: "not-used" });
  const client = new Client({ name: "parity-check", version: "0" });
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  // MCP has no field for what a tool needs from the server, so this side declares it
  // on the op and nowhere else -- over the wire it survives only as a sentence in the
  // description, and `surface.test.ts` is what holds that sentence to the declaration.
  const declaredRequirements = new Map(allOperations.map((op) => [op.name, op.requires]));
  // Also op-side only: MCP has no field for the shape of a result either.
  const declaredResults = new Map(allOperations.map((op) => [op.name, op.result]));
  try {
    const { tools } = await client.listTools();
    return surfaceByName(
      tools.map((t) => {
        const advertised = t as unknown as Record<string, unknown>;
        const where = `${t.name} (advertised)`;
        if (!declaredRequirements.has(t.name)) {
          throw new Error(
            `${t.name} is advertised but is not a registered op, so there is nothing to read ` +
              "what it needs from the server off",
          );
        }
        return [
          t.name,
          {
            inputSchema: (read(advertised, "inputSchema", "object", where) ?? {}) as JsonSchema,
            // No tags: an MCP server advertises the read/write split as a hint or not at all.
            annotations: (read(advertised, "annotations", "object", where) ??
              {}) as ToolAnnotations,
            requires: declaredRequirements.get(t.name),
            result: declaredResults.get(t.name),
          },
        ] as [string, ToolContract];
      }),
      "the advertised tools",
    );
  } finally {
    await client.close();
    await server.close();
  }
}

/**
 * The third surface: the MCP server Galaxy itself serves.
 *
 * `lib/galaxy/webapps/galaxy/api/mcp.py` calls Galaxy's `AgentOperationsManager` in
 * process; this package's Python tools go through bioblend and REST, and the ops here
 * through REST. Three implementations over one Galaxy, so a difference between them is
 * one somebody wrote, on whichever side wrote it. It is read from a snapshot
 * rather than from a running Galaxy: the generator needs a Galaxy checkout, CI has none,
 * and a column that could only be produced on one laptop is no use to a reader. The
 * snapshot says which Galaxy commit it came from, and `builtin_surface.py` says how to
 * refresh it.
 */

/** Which Galaxy the snapshot describes, written by the generator. */
export interface BuiltinProvenance {
  version: string;
  branch: string;
  commit: string;
  describe: string;
  commitDate: string;
  moduleBlob: string;
  fastmcp: string;
  capturedOn: string;
}

export interface BuiltinSnapshot extends Manifest {
  galaxy: BuiltinProvenance;
}

/**
 * What the comparison is told to overlook about the built-in server, each a single
 * switch the registry flips, exactly like the whole-surface rules above.
 *
 * All three describe the same kind of thing: something the built-in says everywhere or
 * nowhere, which would otherwise arrive as one divergence per tool and say the same
 * sentence forty times. Each is checked where it is applied, so a rule that stops being
 * true stops the run instead of quietly hiding a real difference.
 */
export const BUILTIN_RULES = ["builtinApiKey", "builtinMutability", "builtinRequirements"] as const;

export type BuiltinRuleName = (typeof BUILTIN_RULES)[number];

export interface BuiltinRegistry {
  /** Where the snapshot came from, so the registry names the file it is about. */
  source: string;
  /** Built-in tool name -> the name the other two surfaces use for the same tool. */
  aliases: Record<string, string>;
  /** Why each alias is one tool under two names, since nothing else can say it. */
  aliasReason: string;
  normalization: Record<BuiltinRuleName, NormalizationRule>;
  ratchet: Ratchet;
  divergences: AcceptedDivergence[];
}

const BUILTIN_SNAPSHOT_URL = new URL("./galaxy-builtin-surface.json", MANIFEST_URL);

/** What to call the registry's built-in section when something in it cannot be read. */
const BUILTIN_SECTION = 'the registry\'s "builtin" section';

export function loadBuiltinSnapshot(): BuiltinSnapshot {
  return readJson<BuiltinSnapshot>(BUILTIN_SNAPSHOT_URL, "Galaxy built-in surface snapshot");
}

/** The registry's built-in section, read as its own registry. */
export function builtinRegistry(registry: Registry): BuiltinRegistry {
  const node = registry as unknown as Record<string, unknown>;
  const section = read(node, "builtin", "object", "the registry") as BuiltinRegistry | undefined;
  if (!section) {
    throw new Error(
      'the registry has no "builtin" section, and the third surface has nowhere to record ' +
        "what it found",
    );
  }
  const where = BUILTIN_SECTION;
  const declared = new Map(Object.entries(section.normalization ?? {}));
  for (const name of BUILTIN_RULES) {
    const rule = declared.get(name);
    if (!rule) throw new Error(`${where} does not declare the "${name}" rule`);
    if (read(rule as unknown as Record<string, unknown>, "enabled", "boolean", where) === undefined) {
      throw new Error(`${where} does not say whether "${name}" is enabled`);
    }
  }
  return section;
}

const enabled = (section: BuiltinRegistry, rule: BuiltinRuleName): boolean =>
  section.normalization[rule].enabled;

/** How a built-in divergence names its side, and what it is allowed to compare. */
export function builtinSide(section: BuiltinRegistry): OtherSide {
  return {
    label: "builtin",
    missingTool: "missing-builtin-tool",
    missingParam: "missing-builtin-param",
    comparesMutability: !enabled(section, "builtinMutability"),
    comparesRequirements: !enabled(section, "builtinRequirements"),
    // Galaxy's own surface states no result shapes, so there is nothing to compare.
    comparesResults: false,
  };
}

/** The credential every built-in tool takes, which the other two take once per session. */
const API_KEY = "api_key";

function withoutApiKey(tool: ManifestTool, where: string): ManifestTool {
  const schema = tool.inputSchema as unknown as Record<string, unknown>;
  const properties = (read(schema, "properties", "object", where) ?? {}) as Record<string, JsonSchema>;
  const required = (read(schema, "required", "names", where) ?? []) as string[];
  const declared = properties[API_KEY];
  // Checked rather than assumed: the rule is "every built-in tool takes the key as an
  // argument", and the day one stops -- or starts taking it optionally -- somebody has to
  // decide what that means rather than have this quietly drop nothing.
  if (!declared || declared.type !== "string" || !required.includes(API_KEY)) {
    throw new Error(
      `${where}: the "${API_KEY}" rule says every built-in tool takes a required string ` +
        `${JSON.stringify(API_KEY)}, and this one does not; re-read the rule before the ` +
        "comparison drops a parameter it has not understood",
    );
  }
  const rest = { ...properties };
  delete rest[API_KEY];
  return {
    ...tool,
    inputSchema: {
      ...(tool.inputSchema as JsonSchema),
      properties: rest,
      required: required.filter((name) => name !== API_KEY),
    } as JsonSchema,
  };
}

/**
 * The built-in surface as the comparison reads it: aliased to the names the other two
 * surfaces use, without the per-call credential, and without the empty tag list.
 *
 * The empty list is dropped rather than carried because it is not a declaration: every
 * tool is registered with a bare `@mcp.tool()`, so the built-in tells a client nothing
 * about which tools write, and `[]` read as tags would say "this tool is read-only" about
 * all 44. With it gone the surface reads as what a client would have to assume.
 */
export function builtinSurface(snapshot: BuiltinSnapshot, section: BuiltinRegistry): Surface {
  const names = new Set(snapshot.tools.map((tool) => tool.name));
  for (const [from, to] of Object.entries(section.aliases)) {
    if (!names.has(from)) {
      throw new Error(
        `${BUILTIN_SECTION}: "${from}" is aliased to "${to}", and the built-in server has no ` +
          "such tool; an alias nobody can reach hides a rename rather than recording one",
      );
    }
    if (names.has(to)) {
      throw new Error(
        `${BUILTIN_SECTION}: "${from}" is aliased to "${to}", which the built-in server also ` +
          "has, so the two would land on one name and the comparison would lose one of them",
      );
    }
  }
  const tools = snapshot.tools.map((tool) => {
    const at = `${tool.name} (builtin)`;
    if (enabled(section, "builtinMutability") && (tool.tags.length || Object.keys(tool.annotations).length)) {
      throw new Error(
        `${at}: the "builtinMutability" rule says the built-in advertises no tags and no ` +
          "annotations, so the comparison leaves read-versus-write out of it; this tool " +
          "advertises some, and somebody has to decide what the rule means now",
      );
    }
    if (enabled(section, "builtinRequirements") && tool.requires) {
      throw new Error(
        `${at}: the "builtinRequirements" rule says the built-in declares no Galaxy ` +
          "requirement -- it is served BY the Galaxy in question -- and this tool declares one",
      );
    }
    const named = { ...tool, name: section.aliases[tool.name] ?? tool.name };
    return enabled(section, "builtinApiKey") ? withoutApiKey(named, at) : named;
  });
  const surface = pythonSurface({ ...snapshot, tools });
  return new Map(
    [...surface].map(([name, contract]) => {
      if (contract.tags?.length) return [name, contract];
      const { tags: _dropped, ...rest } = contract;
      return [name, rest];
    }),
  );
}
