name: Python Tests

on:
  push:
    branches: [main]
    paths:
      - "mcp-server-galaxy-py/**"
      - ".github/workflows/python-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "mcp-server-galaxy-py/**"
      - ".github/workflows/python-tests.yml"
  workflow_dispatch:

defaults:
  run:
    working-directory: mcp-server-galaxy-py

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Lint with pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure

      - name: Test with pytest
        run: |
          uv run pytest --cov=galaxy_mcp --cov-report=term-missing

  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Type check with mypy
        run: uv run mypy src/galaxy_mcp

  build:
    runs-on: ubuntu-latest
    needs: [test, type-check]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Build package
        run: uv run python -m build

      - name: Check built packages
        run: |
          ls -la dist/
          uv run twine check dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-packages
          path: mcp-server-galaxy-py/dist/
